# Generated by Django 5.1.4 on 2025-02-25 19:25

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/profile_images/Default_profile_image.png', max_length=255, null=True, upload_to=account.models.get_profile_image_filepath),
        ),
    ]
