# Generated by Django 5.1.4 on 2025-03-06 07:53

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/Default_profile_image.png', max_length=255, null=True, upload_to=account.models.get_profile_image_filepath),
        ),
    ]
