# Generated by Django 5.1.4 on 2025-01-16 22:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_remove_checklist_category_remove_checklist_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='due_date',
        ),
        migrations.AddField(
            model_name='checklist',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(help_text='Add an entry to your list.', max_length=200, unique=True),
        ),
    ]
