# Generated by Django 5.1.4 on 2025-02-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_alter_checklist_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
