# Generated by Django 5.1.4 on 2025-01-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_rename_description_entry_notes_remove_entry_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
