# Generated by Django 5.1.4 on 2025-01-23 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_alter_entry_checklist'),

    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entry',
            name='entry_name_case_insensitive_unique',
        ),

        migrations.AlterField(
            model_name='checklist',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(help_text='Add an entry to your list.', max_length=100),
        ),
    ]
