# Generated by Django 5.1.4 on 2025-01-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_remove_checklist_pub_date_entry_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='notes',
        ),
    ]
