# Generated by Django 5.1.4 on 2025-01-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0010_remove_entry_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
