# Generated by Django 5.1.4 on 2025-01-29 15:09

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_alter_checklist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='author',
            field=models.ForeignKey(auto_created=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.RESTRICT, to='checklist.profile'),
        ),
    ]
