# Generated by Django 5.1.4 on 2025-02-12 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0013_alter_checklist_author_alter_entry_checklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['creation_date']},
        ),
    ]
