# Generated by Django 5.1.4 on 2025-02-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0014_alter_entry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/Default_profile_image.png', null=True, upload_to='profile_images/'),
        ),
    ]
