# Generated by Django 5.1.4 on 2025-02-18 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0015_profile_profile_image'),
        ('friend', '0002_alter_friendrequest_unique_together_and_more'),

    ]


    migrations.DeleteModel(
            name='Profile',
        ),
    
