# Generated by Django 5.1.4 on 2025-02-18 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0016_alter_checklist_author_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.DeleteModel(
            name='Profile',
        ),
    ]
